spring:
  profiles:
    active:
    - dev
---
server:
  port: 5555

spring:
  profiles: dev
  application:
    name:  versioncloud-5555-hystrix-config-task
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.31.150:3306/lian2345?useSSL=false     # 数据库名称
    username: root
    password: DaikuanTest888..
    dbcp2:
      min-idle: 50                                           # 数据库连接池的最小维持连接数
      initial-size: 50                                       # 初始化连接数
      max-total: 500                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: update
#    控制台显示SQL
    show-sql: false
    #数据在5.7以上会报错
    database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://www.lian2345.com:7001/eureka/,http://www.lian2345.com:7002/eureka/
  instance:
    instance-id: versioncloud-5555-hystrix-config-task-5555
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
    
info:
   app.name: versioncloud-provieder-task
   company.name: www.lian2345.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
---
server:
  port: 5555

spring:
  profiles: dev5555
  application:
    name:  versioncloud-5555-hystrix-config-task
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.31.150:3306/lian2345?useSSL=false       # 数据库名称
    username: root
    password: DaikuanTest888..
    dbcp2:
      min-idle: 50                                           # 数据库连接池的最小维持连接数
      initial-size: 50                                       # 初始化连接数
      max-total: 500                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: update
#    控制台显示SQL
    show-sql: false
    #数据在5.7以上会报错
    database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: versioncloud-5555-hystrix-config-task-5555
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
    
info:
   app.name: versioncloud-provieder-task
   company.name: www.kpl.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
---
server:
  port: 5554

spring:
  profiles: dev5554
  application:
    name:  versioncloud-5555-hystrix-config-task
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.31.150:3306/lian2345?useSSL=false       # 数据库名称
    username: root
    password: DaikuanTest888..
    dbcp2:
      min-idle: 50                                           # 数据库连接池的最小维持连接数
      initial-size: 50                                       # 初始化连接数
      max-total: 500                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: update
#    控制台显示SQL
    show-sql: false
    #数据在5.7以上会报错
    database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: versioncloud-5555-hystrix-config-task-5554
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
    
info:
   app.name: versioncloud-provieder-task
   company.name: www.kpl.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
---
server:
  port: 5555

spring:
  profiles: test
  application:
    name:  versioncloud-5555-hystrix-config-task
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.31.150:3306/lian2345?useSSL=false     # 数据库名称
    username: root
    password: DaikuanTest888..
    dbcp2:
      min-idle: 50                                           # 数据库连接池的最小维持连接数
      initial-size: 50                                       # 初始化连接数
      max-total: 500                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: update
#    控制台显示SQL
    show-sql: false
    #数据在5.7以上会报错
    database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.31.200:7001/eureka/,http://192.168.31.200:7002/eureka/
  instance:
    instance-id: versioncloud-5555-hystrix-config-task-5555-test
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
    
info:
   app.name: versioncloud-provieder-task-test
   company.name: www.kpl.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$