spring:
  profiles:
    active:
    - dev
---

spring:
  profiles: dev
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://192.168.31.60:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://192.168.31.150:3306/lian2345 # 数据库名称
    username: root
    password: DaikuanTest888..
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间


server:
  port: 7081
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://www.lian2345.com:7001/eureka/,http://www.lian2345.com:7002/eureka/
  instance:
    instance-id: versioncloud-search-admin7081
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
    
info:
   app.name: versioncloud-search-admin7081
   company.name: www.lian2345.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
hystrix:    
  command:    
    default:    
      execution:    
        isolation:    
          thread:    
            timeoutInMilliseconds: 5000
---
spring:
  profiles: dev7081
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://192.168.31.60:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://192.168.31.150:3306/lian2345 # 数据库名称
    username: root
    password: DaikuanTest888..
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间


server:
  port: 7081
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: versioncloud-search-admin7081
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
    
info:
   app.name: versioncloud-search-admin7081
   company.name: www.kpl.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
hystrix:    
  command:    
    default:    
      execution:    
        isolation:    
          thread:    
            timeoutInMilliseconds: 5000
---
spring:
  profiles: dev7082
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://192.168.31.60:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://192.168.31.150:3306/lian2345 # 数据库名称
    username: root
    password: DaikuanTest888..
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间


server:
  port: 7081
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: versioncloud-search-admin7082
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
    
info:
   app.name: versioncloud-search-admin7082
   company.name: www.kpl.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
hystrix:    
  command:    
    default:    
      execution:    
        isolation:    
          thread:    
            timeoutInMilliseconds: 5000
---
spring:
  profiles: test
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://192.168.31.60:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://192.168.31.150:3306/lian2345 # 数据库名称
    username: root
    password: DaikuanTest888..
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间


server:
  port: 7081
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.31.200:7001/eureka/,http://192.168.31.200:7002/eureka/
  instance:
    instance-id: versioncloud-search-admin7082-test
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
    
info:
   app.name: versioncloud-search-admin7082-test
   company.name: www.kpl.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
hystrix:    
  command:    
    default:    
      execution:    
        isolation:    
          thread:    
            timeoutInMilliseconds: 5000
---
spring:
  profiles: test01
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://192.168.31.60:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://192.168.31.150:3306/lian2345 # 数据库名称
    username: root
    password: DaikuanTest888..
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间


server:
  port: 7081
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.31.200:7001/eureka/,http://192.168.31.200:7002/eureka/
  instance:
    instance-id: versioncloud-search-admin7082-test-01
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
    
info:
   app.name: versioncloud-search-admin7082-test-01
   company.name: www.kpl.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
hystrix:    
  command:    
    default:    
      execution:    
        isolation:    
          thread:    
            timeoutInMilliseconds: 5000
---
spring:
  profiles: test02
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://192.168.31.60:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://192.168.31.150:3306/lian2345 # 数据库名称
    username: root
    password: DaikuanTest888..
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间


server:
  port: 7081
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.31.225:7001/eureka/,http://192.168.31.225:7002/eureka/
  instance:
    instance-id: versioncloud-search-admin7082-test-02
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
    
info:
   app.name: versioncloud-search-admin7082-test-02
   company.name: www.kpl.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
hystrix:    
  command:    
    default:    
      execution:    
        isolation:    
          thread:    
            timeoutInMilliseconds: 5000