spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: test1122
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://47.75.146.74:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://127.0.0.1:3306/lian2345?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=100      # 数据库名称
    username: root
    password: DaikuanTest888..
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#mongo配置
  data:
    mongodb:
      database: lian2345
      uri: mongodb://47.75.146.74:27017

server:
  port: 7081
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400
---
spring:
  profiles: zhanqun01
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://47.75.146.74:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://127.0.0.1:3306/8bitcash?characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=100      # 数据库名称
    username: root
    password: root
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#mongo配置
  data:
    mongodb:
      database: 8bitcash
      uri: mongodb://47.75.146.74:27017

server:
  port: 7081
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400
---
spring:
  profiles: zhanqun02
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://47.75.146.74:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://127.0.0.1:3306/8bittoken?characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=100      # 数据库名称
    username: root
    password: root
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#mongo配置
  data:
    mongodb:
      database: 8bittoken
      uri: mongodb://47.75.146.74:27017

server:
  port: 7082
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400
---
spring:
  profiles: zhanqun03
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://47.75.146.74:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://127.0.0.1:3306/bit001?characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=100      # 数据库名称
    username: root
    password: root
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#mongo配置
  data:
    mongodb:
      database: bit001
      uri: mongodb://47.75.146.74:27017

server:
  port: 7083
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400
---
spring:
  profiles: zhanqun04
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://47.75.146.74:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://127.0.0.1:3306/bitball?characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=100      # 数据库名称
    username: root
    password: root
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#mongo配置
  data:
    mongodb:
      database: bitball
      uri: mongodb://47.75.146.74:27017

server:
  port: 7084
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400
---
spring:
  profiles: zhanqun05
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://47.75.146.74:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://127.0.0.1:3306/8bitcash?characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=100      # 数据库名称
    username: root
    password: root
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#mongo配置
  data:
    mongodb:
      database: 8bitcash
      uri: mongodb://47.75.146.74:27017

server:
  port: 7081
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400
---
spring:
  profiles: zhanqun06
  application:
    name:  versioncloud-search-admin
  elasticsearch:
    jest:
      uris:
      - http://47.75.146.74:9200
      read-timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    url: jdbc:mysql://127.0.0.1:3306/bit002?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true      # 数据库名称
    username: root
    password: root
    dbcp2:
      driver-class-name: org.gjt.mm.mysql.Driver
#      dbcp2:
#        min-idle: 5                                           # 数据库连接池的最小维持连接数
#        initial-size: 5                                       # 初始化连接数
#        max-total: 5                                          # 最大连接数
#        max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#mongo配置
  data:
    mongodb:
      database: bit002
      uri: mongodb://47.75.146.74:27017

server:
  port: 7088
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400
---